### ISSUE TITLE
NPE when query made via ES Java client

### ISSUE THREAD

**Issue by echarles** [crate/elasticsearch-timefacets-plugin#8]
The elasticsearch-timefacets-plugin works fine via REST but gives an NullPointerException when the query is done with the JAVA client (Netty serialization).

I have just experienced this, and it has also been reported by a user an the elasticsearch mailing list 8 months ago.

https://groups.google.com/forum/#!msg/elasticsearch/kuqXGlqgTwc/O2Ac4o--fDoJ

A workaround/fixe is to return the built-in InternalCountDateHistogramFacet instead of the InternalDistinctDateHistogramFacet.

I will create a pull-request to further discuss this.

**Comment by mfussenegger** [comment]
Thanks for the report.

What version of the plugin are you using? I can't really reproduce the issue with the example given in the mailing list, but since it's 8 month old it was before the refactoring we did for 0.90 compatibility.

**Comment by echarles** [comment]
I use HEAD from master, deployed on ES 0.90.0. Are you using the JAVA client. Yes, it works fine via REST but fails via the Netty serialization.

**Comment by mfussenegger** [comment]
We use the java transport client in the tests (DistinctDateHistogramFacetTests in this case) and start several nodes so that serialization is also tested. 

Can you also paste the exact (facet)query and stacktrace?

**Comment by echarles** [comment]
damned it, I can't reproduce it.

Checkout https://github.com/echarles/elasticsearch-timefacets-plugin/commit/f8b12d28498110b851677914095186a1aa6b7697

The issue I have is with data I can not disclose. REST and unit test with embedded node are fine. Only with remote access (InetSocketTransportAddress) gives an exception.

The unit test I have added launches a ES server and connects to it via InetSocketTransportAddress. But still, I can not reproduce the issue (although I have defined some nested field to make it a bit more tricky) - see the root cause NPE.

org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.elasticsearch.action.search.SearchResponse]
    at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:150)
    at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:127)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
    at org.elasticsearch.search.facet.InternalFacets.readFrom(InternalFacets.java:144)
    at org.elasticsearch.search.facet.InternalFacets.readFacets(InternalFacets.java:130)
    at org.elasticsearch.search.internal.InternalSearchResponse.readFrom(InternalSearchResponse.java:99)
    at org.elasticsearch.search.internal.InternalSearchResponse.readInternalSearchResponse(InternalSearchResponse.java:91)
    at org.elasticsearch.action.search.SearchResponse.readFrom(SearchResponse.java:219)
    at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:148)
    ... 23 more

**Comment by echarles** [comment]
Last update: if you run the unit test, you won't get the exception.

However, if you deploy the plugin to a separate ES server instance, comment lines 29-34 of DistinctDateHistogramFacetRemoteTest, and run the test, you will get the NPE.

**Comment by mfussenegger** [comment]
Thanks for the feedback. 

I've been able to reproduce the error and should be able to come up with a solution soon.

**Comment by echarles** [comment]
Cool!

Tell me if you need help for test... Btw, I have a workaround that returns the built-in internal date histogram facet. It works fine, but maybe you will come with a better solution.

**Comment by mfussenegger** [comment]
#9 should fix your issue. If that's not the case please reopen the issue.

**Comment by echarles** [comment]
Thx. I pull the new 0.8.1 version with the changes and deployed that new plugin on a test cluster (0.9.0)
The server does not start - no exception shown in the log.

Did you try to deploy on a server?

**Comment by mfussenegger** [comment]
Yes I did. Worked fine, but we're on 0.90.2

Can you start a node locally with the plugin loaded?

**Comment by echarles** [comment]
I tried on our staging server (multiple node) as on a local single node and it does not start (no exception in the log).

**Comment by mfussenegger** [comment]
Can you provide some details on how you packaged and installed the plugins and how you run elasticsearch? (on the local single node?)
